### ISSUE TITLE
Proposal: Tonk should check all roles for administrator and manager roles, not just the top role.

### ISSUE THREAD

**Issue by beemancer** [ahinh43/tonk#2]
Checking only the top role creates a few problems for server administrators involving role management.  The hierarchy of roles in discord determine which roles are the most prevalent as well as determining the user's color.  In our server, we generally let anyone start the MPAs in the selected channels, so the role used to manage MPAs is freely assignable.  However, we need to keep this role near the top of the role list even though it has no additional privileges, and we cannot assign this role a color because then everyone else's text colors would be set to that role.

**Comment by ahinh43** [comment]
This should be adjusted now to compare all roles of the person who calls manager type commands instead of looking only at the top role.

Change is live on the bot. Give it a try in your server and let me know how it goes!

**Comment by beemancer** [comment]
Can confirm that manager role is checked among all roles, although admin is not.  Admin doesn't matter for my server, at least, since we keep our admin roles at the top.

Thanks for this!
